baseurl = "https://nyzme.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Jordan Balintac"
title = "nyzme"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "My personal blog"
copyright = "Copyright © 2018"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "jbalintac"
email = ""
linkedin = "jbalintac"
twitter = ""
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false